#!/usr/bin/env bash
# commit-msg hook: enforces Conventional Commits and rejects any AI attribution.
set -euo pipefail

msg_file="$1"
# Drop git comment lines; keep the rest for checks.
body="$(grep -v '^#' "$msg_file" || true)"
subject="$(printf '%s\n' "$body" | sed '/^[[:space:]]*$/d' | head -n 1)"

fail() {
  printf '\n\033[31m✖ Commit refusé :\033[0m %s\n\n' "$1" >&2
  exit 1
}

[ -n "$subject" ] || fail "message vide."

# Messages generated by git itself are allowed as-is.
if [[ "$subject" =~ ^(Merge |Revert \"|fixup! |squash! |amend! ) ]]; then
  exit 0
fi

types='feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert'
pattern="^(${types})(\([a-zA-Z0-9._/-]+\))?!?: [^[:space:]].{0,99}$"
if ! [[ "$subject" =~ $pattern ]]; then
  fail "le titre ne respecte pas Conventional Commits.
  Reçu   : $subject
  Attendu: type(scope optionnel): description   (100 caractères max)
  Types  : ${types//|/, }
  Exemple: feat(auth): add password reset"
fi

ai_pattern='claude|anthropic|chatgpt|openai|copilot|gemini|cursor ai|generated (with|by)|ai-generated|co-authored-by:.*(bot|ai)|🤖'
if printf '%s\n' "$body" | grep -Eiq "$ai_pattern"; then
  line="$(printf '%s\n' "$body" | grep -Ein "$ai_pattern" | head -n 1)"
  fail "le message mentionne un outil d'IA (ligne ${line%%:*}) : ${line#*:}"
fi
